// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-starter/internal/dao/internal"
)

// internalButtonDao is internal type for wrapping internal DAO implements.
type internalButtonDao = *internal.ButtonDao

// buttonDao is the data access object for table button.
// You can define custom methods on it to extend its functionality as you wish.
type buttonDao struct {
	internalButtonDao
}

var (
	// Button is globally public accessible object for table button operations.
	Button = buttonDao{
		internal.NewButtonDao(),
	}
)

// Fill with you ideas below.
