// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-starter/internal/dao/internal"
)

// internalCasbinPolicyDao is internal type for wrapping internal DAO implements.
type internalCasbinPolicyDao = *internal.CasbinPolicyDao

// casbinPolicyDao is the data access object for table casbin_policy.
// You can define custom methods on it to extend its functionality as you wish.
type casbinPolicyDao struct {
	internalCasbinPolicyDao
}

var (
	// CasbinPolicy is globally public accessible object for table casbin_policy operations.
	CasbinPolicy = casbinPolicyDao{
		internal.NewCasbinPolicyDao(),
	}
)

// Fill with you ideas below.
