// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-starter/internal/dao/internal"
)

// internalFileDao is internal type for wrapping internal DAO implements.
type internalFileDao = *internal.FileDao

// fileDao is the data access object for table file.
// You can define custom methods on it to extend its functionality as you wish.
type fileDao struct {
	internalFileDao
}

var (
	// File is globally public accessible object for table file operations.
	File = fileDao{
		internal.NewFileDao(),
	}
)

// Fill with you ideas below.
