// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-starter/internal/dao/internal"
)

// internalLoginLogDao is internal type for wrapping internal DAO implements.
type internalLoginLogDao = *internal.LoginLogDao

// loginLogDao is the data access object for table login_log.
// You can define custom methods on it to extend its functionality as you wish.
type loginLogDao struct {
	internalLoginLogDao
}

var (
	// LoginLog is globally public accessible object for table login_log operations.
	LoginLog = loginLogDao{
		internal.NewLoginLogDao(),
	}
)

// Fill with you ideas below.
