// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-starter/internal/dao/internal"
)

// internalNoticeDao is internal type for wrapping internal DAO implements.
type internalNoticeDao = *internal.NoticeDao

// noticeDao is the data access object for table notice.
// You can define custom methods on it to extend its functionality as you wish.
type noticeDao struct {
	internalNoticeDao
}

var (
	// Notice is globally public accessible object for table notice operations.
	Notice = noticeDao{
		internal.NewNoticeDao(),
	}
)

// Fill with you ideas below.
