// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-starter/internal/dao/internal"
)

// internalOtpAuthDao is internal type for wrapping internal DAO implements.
type internalOtpAuthDao = *internal.OtpAuthDao

// otpAuthDao is the data access object for table otp_auth.
// You can define custom methods on it to extend its functionality as you wish.
type otpAuthDao struct {
	internalOtpAuthDao
}

var (
	// OtpAuth is globally public accessible object for table otp_auth operations.
	OtpAuth = otpAuthDao{
		internal.NewOtpAuthDao(),
	}
)

// Fill with you ideas below.
