// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-starter/internal/dao/internal"
)

// internalUserRelationDao is internal type for wrapping internal DAO implements.
type internalUserRelationDao = *internal.UserRelationDao

// userRelationDao is the data access object for table user_relation.
// You can define custom methods on it to extend its functionality as you wish.
type userRelationDao struct {
	internalUserRelationDao
}

var (
	// UserRelation is globally public accessible object for table user_relation operations.
	UserRelation = userRelationDao{
		internal.NewUserRelationDao(),
	}
)

// Fill with you ideas below.
